apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: buildah-gitlab-pipeline
spec:
  params:
  - name: event-type
    type: string
    description: "The event type"
  resources: 
  - name: git-source
    type: git
  - name: docker-image
    type: image
  tasks:
  - name: build-simple
    taskRef:
      name: buildah
    resources:
      inputs:
      - name: source
        resource: git-source
      outputs:
      - name: image
        resource: docker-image
  - name: deploy-simple
    conditions:
    - conditionRef: deployment-condition
      params:
      - name: event-type
        value: $(params.event-type)
    runAfter: [build-simple]
    taskRef: 
      name: deploy-simple-kubectl-task
    resources: 
      inputs:
      - name: git-source
        resource: git-source 
      - name: image-out
        resource: docker-image