apiVersion: tekton.dev/v1alpha1
kind: Condition
metadata:
  name: deployment-condition
spec:
  params:
  - name: "event-type"
    type: string
    description: "The Git event type"
  check:
    name: deployment-condition
    image: alpine
    command:
      - "/bin/sh"
    args:
      - '-ce'
      - "[[ \"$(params.event-type)\" != \"Merge Request Hook\" ]]"
